services:
  apps:
    build:
      context: .
      target: apps
    volume:
      - apps:/var/www/apps
      - apps_data:/var/www/data
      - conf:/var/www/conf

  php:
    build:
      context: .
      target: php
    restart: unless-stopped
    volume:
      - sock:/sock
      - apps:/var/www/apps
      - apps_data:/var/www/data

  web:
    build:
      context: .
      target: web
    expose:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    volume:
      - sock:/sock
      - apps:/var/www/apps
      - apps_data:/var/www/data
      - conf:/var/www/conf

volumes:
  apps_data:
